window.StrawberryFarm = window.StrawberryFarm || {};

window.StrawberryFarm.config = {
  title: "Fazenda de Morangos",
  storageKey: "strawberry-farm-save",
  initialPlotCount: 6,
  maxPlotCount: 16,
  winMoney: 35,
  autosaveIntervalMs: 4000,
  prestige: {
    label: "Conhecimento do Morango",
    baseThresholdMoney: 120,
    sellBonusPerLevel: 0.2,
    description: "Reinicie para ganhar +20% permanente nas vendas por nível.",
  },
  market: {
    basePrice: 3,
    minPrice: 2,
    maxPrice: 5,
    updateIntervalMs: 12000,
    stepOptions: [-1, 0, 1],
  },
  combo: {
    windowMs: 1800,
    thresholds: [
      { count: 3, moneyBonus: 1 },
      { count: 5, moneyBonus: 2 },
    ],
  },
  crop: {
    name: "Morango",
    growthTimeMs: 10000,
    spoilTimeMs: 6000,
    harvestYield: 1,
    sellPrice: 3,
    seedPrice: 2,
  },
  upgrades: {
    fertilizer: {
      label: "Adubo rápido",
      baseCost: 10,
      costStep: 8,
      maxLevel: 3,
      growthMultiplierPerLevel: 0.75,
      description: "Cada nível reduz 25% do tempo de crescimento.",
    },
    market: {
      label: "Caixa premium",
      baseCost: 14,
      costStep: 10,
      maxLevel: 3,
      sellPriceBonusPerLevel: 2,
      description: "Cada nível adiciona +2 moedas por venda.",
    },
    helper: {
      label: "Ajudante",
      cost: 18,
      harvestIntervalMs: 3500,
      description: "Colhe 1 pronto por ciclo.",
    },
    helperPlanting: {
      label: "Bolsa de sementes",
      cost: 22,
      description: "O ajudante planta 1 vazio por ciclo se não houver colheita. Consome sementes.",
    },
    helperGloves: {
      label: "Luvas Resistentes",
      cost: 25,
      description: "O ajudante limpa 1 canteiro apodrecido por ciclo.",
    },
  },
  farmLevels: [
    { level: 0, label: "3x2", cols: 3, rows: 2, unlockedPlotCount: 6, expansionCost: 0 },
    { level: 1, label: "3x3", cols: 3, rows: 3, unlockedPlotCount: 9, expansionCost: 8 },
    { level: 2, label: "4x3", cols: 4, rows: 3, unlockedPlotCount: 12, expansionCost: 10 },
    { level: 3, label: "4x4", cols: 4, rows: 4, unlockedPlotCount: 16, expansionCost: 12 },
  ],
  expansion: {
    label: "Expandir fazenda",
    description: "Desbloqueie o próximo tamanho da fazenda.",
  },
  events: {
    durationMs: 12000,
    triggerChanceOnSell: 0.35,
    definitions: [
      {
        id: "sunshine",
        title: "Sol forte",
        description: "+1 moeda por venda.",
        type: "sellBonus",
        sellPriceBonus: 1,
        accentClass: "event-banner--sunshine",
      },
      {
        id: "drizzle",
        title: "Chuva leve",
        description: "Crescimento acelerado.",
        type: "growthBoost",
        growthMultiplier: 0.8,
        activePlotRemainingMultiplier: 0.8,
        accentClass: "event-banner--drizzle",
      },
      {
        id: "market-day",
        title: "Feira local",
        description: "Sementes com desconto.",
        type: "seedDiscount",
        seedPriceDiscount: 1,
        accentClass: "event-banner--market",
      },
      {
        id: "pest",
        title: "Praga!",
        description: "Preço de venda reduzido.",
        type: "sellPenalty",
        sellPricePenalty: 1,
        accentClass: "event-banner--pest",
      },
    ],
  },
  progressionGoals: [
    {
      id: "harvest-3",
      title: "Primeira colheita",
      description: "Colha 4 morangos ao todo.",
      targetType: "harvestedTotal",
      targetValue: 4,
      reward: {
        money: 4,
      },
    },
    {
      id: "expand-farm",
      title: "Fazenda maior",
      description: "Expanda a fazenda pelo menos uma vez.",
      targetType: "expandedFarm",
      targetValue: 1,
      reward: {
        seeds: 4,
      },
    },
    {
      id: "buy-upgrade",
      title: "Ferramentas melhores",
      description: "Compre 2 melhorias.",
      targetType: "upgradesPurchased",
      targetValue: 2,
      reward: {
        money: 5,
      },
    },
    {
      id: "reach-35",
      title: "Fazenda rentável",
      description: "Alcance 35 moedas.",
      targetType: "money",
      targetValue: 35,
      reward: null,
    },
    {
      id: "sell-20",
      title: "Comerciante",
      description: "Venda 20 morangos no total.",
      targetType: "soldTotal",
      targetValue: 20,
      reward: { money: 6 },
    },
    {
      id: "harvest-50",
      title: "Colheita farta",
      description: "Colha 50 morangos ao todo.",
      targetType: "harvestedTotal",
      targetValue: 50,
      reward: { money: 8, seeds: 4 },
    },
    {
      id: "all-upgrades",
      title: "Fazenda completa",
      description: "Compre todas as melhorias.",
      targetType: "upgradesPurchased",
      targetValue: 5,
      reward: { money: 12 },
    },
    {
      id: "prestige-1",
      title: "Fazendeiro de prestígio",
      description: "Faça o primeiro prestígio.",
      targetType: "prestigeLevel",
      targetValue: 1,
      reward: { seeds: 5 },
    },
  ],
  startingState: {
    money: 6,
    seeds: 3,
    strawberries: 0,
  },
  plotStates: {
    empty: "empty",
    growing: "growing",
    ready: "ready",
    rotten: "rotten",
  },
};
