(function (SF) {
  SF.ui = SF.ui || {};

  function collectElements() {
    return {
      moneyCount: document.querySelector("#moneyCount"),
      seedCount: document.querySelector("#seedCount"),
      berryCount: document.querySelector("#berryCount"),
      moneyCard: document.querySelector("#moneyCard"),
      seedCard: document.querySelector("#seedCard"),
      berryCard: document.querySelector("#berryCard"),
      growthTimeValue: document.querySelector("#growthTimeValue"),
      growthTimeCard: document.querySelector("#growthTimeCard"),
      plotCountValue: document.querySelector("#plotCountValue"),
      plotCountCard: document.querySelector("#plotCountCard"),
      helperStatusValue: document.querySelector("#helperStatusValue"),
      helperStatusHint: document.querySelector("#helperStatusHint"),
      prestigeLevelValue: document.querySelector("#prestigeLevelValue"),
      prestigeBonusHint: document.querySelector("#prestigeBonusHint"),
      helpPanel: document.querySelector("#helpPanel"),
      helpToggleButton: document.querySelector("#helpToggleButton"),
      helpDismissButton: document.querySelector("#helpDismissButton"),
      statusMessage: document.querySelector("#statusMessage"),
      focusStrip: document.querySelector("#focusStrip"),
      focusStripEyebrow: document.querySelector("#focusStripEyebrow"),
      focusStripTitle: document.querySelector("#focusStripTitle"),
      focusStripText: document.querySelector("#focusStripText"),
      focusStripTimer: document.querySelector("#focusStripTimer"),
      focusStripProgress: document.querySelector("#focusStripProgress"),
      focusStripProgressBar: document.querySelector("#focusStripProgressBar"),
      milestoneToast: document.querySelector("#milestoneToast"),
      milestoneToastText: document.querySelector("#milestoneToastText"),
      saveStatus: document.querySelector("#saveStatus"),
      eventBanner: document.querySelector("#eventBanner"),
      eventTitle: document.querySelector("#eventTitle"),
      eventDescription: document.querySelector("#eventDescription"),
      eventEffect: document.querySelector("#eventEffect"),
      eventTags: document.querySelector("#eventTags"),
      eventTimer: document.querySelector("#eventTimer"),
      eventProgressBar: document.querySelector("#eventProgressBar"),
      marketBanner: document.querySelector("#marketBanner"),
      marketHeadline: document.querySelector("#marketHeadline"),
      marketSummary: document.querySelector("#marketSummary"),
      marketEffect: document.querySelector("#marketEffect"),
      marketPriceValue: document.querySelector("#marketPriceValue"),
      marketChangeIndicator: document.querySelector("#marketChangeIndicator"),
      marketTimer: document.querySelector("#marketTimer"),
      prestigePanel: document.querySelector("#prestigePanel"),
      prestigePanelTitle: document.querySelector("#prestigePanelTitle"),
      prestigePanelDescription: document.querySelector("#prestigePanelDescription"),
      prestigeThresholdText: document.querySelector("#prestigeThresholdText"),
      progressSummary: document.querySelector("#progressSummary"),
      sidebarGoalsTab: document.querySelector("#sidebarGoalsTab"),
      sidebarUpgradesTab: document.querySelector("#sidebarUpgradesTab"),
      sidebarGuideTab: document.querySelector("#sidebarGuideTab"),
      progressionPanel: document.querySelector("#progressionPanel"),
      upgradesPanel: document.querySelector("#upgradesPanel"),
      goalList: document.querySelector("#goalList"),
      farmGrid: document.querySelector("#farmGrid"),
      buySeedButton: document.querySelector("#buySeedButton"),
      sellButton: document.querySelector("#sellButton"),
      resetButton: document.querySelector("#resetButton"),
      fertilizerButton: document.querySelector("#fertilizerButton"),
      marketButton: document.querySelector("#marketButton"),
      expandFarmButton: document.querySelector("#expandFarmButton"),
      helperButton: document.querySelector("#helperButton"),
      prestigeButton: document.querySelector("#prestigeButton"),
      fertilizerDescription: document.querySelector("#fertilizerDescription"),
      fertilizerLevelMeta: document.querySelector("#fertilizerLevelMeta"),
      marketDescription: document.querySelector("#marketDescription"),
      marketLevelMeta: document.querySelector("#marketLevelMeta"),
      expansionDescription: document.querySelector("#expansionDescription"),
      helperLevelMeta: document.querySelector("#helperLevelMeta"),
      helperDescription: document.querySelector("#helperDescription"),
    };
  }

  SF.ui.collectElements = collectElements;
})(window.StrawberryFarm = window.StrawberryFarm || {});
