(function (SF) {
  SF.ui = SF.ui || {};

  function collectElements() {
    return {
      moneyCount: document.querySelector("#moneyCount"),
      seedCount: document.querySelector("#seedCount"),
      berryCount: document.querySelector("#berryCount"),
      moneyCard: document.querySelector("#moneyCard"),
      seedCard: document.querySelector("#seedCard"),
      berryCard: document.querySelector("#berryCard"),
      sellPriceValue: document.querySelector("#sellPriceValue"),
      sellPriceHint: document.querySelector("#sellPriceHint"),
      sellPriceCard: document.querySelector("#sellPriceCard"),
      growthTimeValue: document.querySelector("#growthTimeValue"),
      growthTimeCard: document.querySelector("#growthTimeCard"),
      plotCountValue: document.querySelector("#plotCountValue"),
      plotCountCard: document.querySelector("#plotCountCard"),
      helperCard: document.querySelector("#helperCard"),
      helperStatusValue: document.querySelector("#helperStatusValue"),
      helperStatusHint: document.querySelector("#helperStatusHint"),
      prestigeCard: document.querySelector("#prestigeCard"),
      prestigeLevelValue: document.querySelector("#prestigeLevelValue"),
      prestigeBonusHint: document.querySelector("#prestigeBonusHint"),
      goalStatus: document.querySelector("#goalStatus"),
      helpPanel: document.querySelector("#helpPanel"),
      helpToggleButton: document.querySelector("#helpToggleButton"),
      helpDismissButton: document.querySelector("#helpDismissButton"),
      statusMessage: document.querySelector("#statusMessage"),
      comboStrip: document.querySelector("#comboStrip"),
      comboTitle: document.querySelector("#comboTitle"),
      comboText: document.querySelector("#comboText"),
      comboTimer: document.querySelector("#comboTimer"),
      comboProgressBar: document.querySelector("#comboProgressBar"),
      helperStrip: document.querySelector("#helperStrip"),
      helperStripTitle: document.querySelector("#helperStripTitle"),
      helperStripText: document.querySelector("#helperStripText"),
      helperStripTimer: document.querySelector("#helperStripTimer"),
      milestoneToast: document.querySelector("#milestoneToast"),
      milestoneToastText: document.querySelector("#milestoneToastText"),
      saveStatus: document.querySelector("#saveStatus"),
      moneyGoalProgressLabel: document.querySelector("#moneyGoalProgressLabel"),
      moneyGoalProgressBar: document.querySelector("#moneyGoalProgressBar"),
      readyPlotProgressLabel: document.querySelector("#readyPlotProgressLabel"),
      readyPlotProgressBar: document.querySelector("#readyPlotProgressBar"),
      eventBanner: document.querySelector("#eventBanner"),
      eventTitle: document.querySelector("#eventTitle"),
      eventDescription: document.querySelector("#eventDescription"),
      eventEffect: document.querySelector("#eventEffect"),
      eventTags: document.querySelector("#eventTags"),
      eventTimer: document.querySelector("#eventTimer"),
      eventProgressBar: document.querySelector("#eventProgressBar"),
      marketBanner: document.querySelector("#marketBanner"),
      marketHeadline: document.querySelector("#marketHeadline"),
      marketSummary: document.querySelector("#marketSummary"),
      marketEffect: document.querySelector("#marketEffect"),
      marketPriceValue: document.querySelector("#marketPriceValue"),
      marketChangeIndicator: document.querySelector("#marketChangeIndicator"),
      marketTimer: document.querySelector("#marketTimer"),
      prestigePanel: document.querySelector("#prestigePanel"),
      prestigePanelTitle: document.querySelector("#prestigePanelTitle"),
      prestigePanelDescription: document.querySelector("#prestigePanelDescription"),
      prestigeThresholdText: document.querySelector("#prestigeThresholdText"),
      progressSummary: document.querySelector("#progressSummary"),
      sidebarGoalsTab: document.querySelector("#sidebarGoalsTab"),
      sidebarUpgradesTab: document.querySelector("#sidebarUpgradesTab"),
      sidebarGuideTab: document.querySelector("#sidebarGuideTab"),
      progressionPanel: document.querySelector("#progressionPanel"),
      upgradesPanel: document.querySelector("#upgradesPanel"),
      goalList: document.querySelector("#goalList"),
      farmGrid: document.querySelector("#farmGrid"),
      buySeedButton: document.querySelector("#buySeedButton"),
      sellButton: document.querySelector("#sellButton"),
      resetButton: document.querySelector("#resetButton"),
      fertilizerButton: document.querySelector("#fertilizerButton"),
      marketButton: document.querySelector("#marketButton"),
      expandFarmButton: document.querySelector("#expandFarmButton"),
      helperButton: document.querySelector("#helperButton"),
      prestigeButton: document.querySelector("#prestigeButton"),
      fertilizerDescription: document.querySelector("#fertilizerDescription"),
      fertilizerLevelMeta: document.querySelector("#fertilizerLevelMeta"),
      marketDescription: document.querySelector("#marketDescription"),
      marketLevelMeta: document.querySelector("#marketLevelMeta"),
      expansionDescription: document.querySelector("#expansionDescription"),
      helperLevelMeta: document.querySelector("#helperLevelMeta"),
      helperDescription: document.querySelector("#helperDescription"),
    };
  }

  SF.ui.collectElements = collectElements;
})(window.StrawberryFarm = window.StrawberryFarm || {});
